#! /bin/bash

cd /home/$USER/.config/fetchinfo/
. config
echo 0 > .tmp

get_pic () {
	echo $(( $(cat .tmp)+1 )) >.tmp
    pic=$(sed -n $(cat .tmp)"p" $image )
    pic=${pic::-1}
	echo -e "$pic"
}

name="$USER@$(cat /etc/hostname)"
echo -e "${Color}$(get_pic)${Color2}$name${NoColor}"

lname=${#name}
for (( r=1 ; r<=$lname ; r++ ));
do
    u=$u$ULine

done

echo -e "${Color}$(get_pic)${Color3}$u${NoColor}"
echo -e "${Color}$(get_pic)${NoColor}"

for dir in *.conf
do
    . $dir
    fname=${dir:2:-5}
    echo -e "${Color}$(get_pic)${Color2}$fname: ${Color3}${!fname}${NoColor}"
done

while [ "$(cat .tmp)" != "$(wc -l < image)" ];
do
    echo -e "${Color}$(get_pic)${NoColor}"
done
